api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Domain/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: 'Test Task API'
    version: '1.0.0'
    resource_class_directories:
        - '%kernel.project_dir%/src/Domain/Entity'
