version: '3.8'

services:
  test-task-php-fpm:
    dns:
      - 8.8.8.8
    build:
      context: php-fpm
    volumes:
      - ../../:/app
      - ./php-fpm/conf.d/api-platform.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - test-task-mongo
    working_dir: /app
    networks:
      - test-task

  test-task-mailer:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
    networks:
      - test-task

  test-task-nginx:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    restart: on-failure
    working_dir: /app
    volumes:
      - ../..//public:/app
      - ./nginx/templates:/etc/nginx/templates:cached
    depends_on:
      - test-task-php-fpm
    networks:
      - test-task
    environment:
      - VIRTUAL_HOST=${TEST_TASK_SERVICE_DOMAIN}

  test-task-mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - test-task

networks:
  test-task: