services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Application\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]

    App\Infrastructure\Doctrine\Listener\MovieSetOwnerListener:
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: prePersist }

    App\Infrastructure\Doctrine\Extension\MovieCurrentUserOwnerExtension:
        tags:
            - { name: api_platform.doctrine_mongodb.odm.aggregation_extension.collection }
            - { name: api_platform.doctrine_mongodb.odm.aggregation_extension.item }

    App\Domain\Service\MovieService:
        arguments:
            $sender: '%env(MAILER_SENDER)%'

    App\Domain\Service\UserService:
        arguments:
            $objectManager: '@doctrine_mongodb.odm.default_document_manager'